// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQErjgyBfLsBBtaudrEnD4g1utUBqlb6A',
    appId: '1:981421958272:web:5a3d82fbf648507f3e3265',
    messagingSenderId: '981421958272',
    projectId: 'eventosapp-d7729',
    authDomain: 'eventosapp-d7729.firebaseapp.com',
    storageBucket: 'eventosapp-d7729.firebasestorage.app',
    measurementId: 'G-3DGG5TTWVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlL3P7M82WtfnysNYaGI_g7oer79HuICM',
    appId: '1:981421958272:android:a6a62e5fd3b6b1ea3e3265',
    messagingSenderId: '981421958272',
    projectId: 'eventosapp-d7729',
    storageBucket: 'eventosapp-d7729.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRXirzcx-cDMU5e7-8Ryr9hWe56Cv-qpQ',
    appId: '1:981421958272:ios:bd37de991c5083293e3265',
    messagingSenderId: '981421958272',
    projectId: 'eventosapp-d7729',
    storageBucket: 'eventosapp-d7729.firebasestorage.app',
    iosBundleId: 'com.example.eventosAppCliente',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRXirzcx-cDMU5e7-8Ryr9hWe56Cv-qpQ',
    appId: '1:981421958272:ios:bd37de991c5083293e3265',
    messagingSenderId: '981421958272',
    projectId: 'eventosapp-d7729',
    storageBucket: 'eventosapp-d7729.firebasestorage.app',
    iosBundleId: 'com.example.eventosAppCliente',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQErjgyBfLsBBtaudrEnD4g1utUBqlb6A',
    appId: '1:981421958272:web:b08a50578d8df6de3e3265',
    messagingSenderId: '981421958272',
    projectId: 'eventosapp-d7729',
    authDomain: 'eventosapp-d7729.firebaseapp.com',
    storageBucket: 'eventosapp-d7729.firebasestorage.app',
    measurementId: 'G-ST92K1G39J',
  );
}
